version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: some_password
      MYSQL_ROOT_PASSWORD: some_password
      # MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
